version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-hyuji
    restart: always
    env_file: .env.production 
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - hyuji_yoyaku_mysql_data:/var/lib/mysql 
    networks:
      - hyuji_yoyaku-backend

  backend:
    build: ./backend
    container_name: hyuji-backend
    restart: always
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=db 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=3001
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=${API_DOMAIN}
    depends_on:
      - db
    networks:
      - hyuji_yoyaku-backend
      - beurre_mou_proxy-tier 

  frontend:
    build: ./frontend
    container_name: hyuji-frontend
    restart: always
    env_file: .env.production
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
      - VITE_API_URL=${BACKEND_DOMAIN}
    networks:
      - hyuji_yoyaku-backend 
      - beurre_mou_proxy-tier 

volumes:
  hyuji_yoyaku_mysql_data:

networks:
  hyuji_yoyaku-backend:
    driver: bridge
  beurre_mou_proxy-tier:
    external: true